# Generated by Django 2.1.2 on 2018-10-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q5', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='next_episode',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='next_season',
            field=models.DateField(blank=True, null=True),
        ),
    ]
